# Generated by Django 4.0.3 on 2022-03-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_account_uploads_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
