# Generated by Django 4.0.3 on 2022-03-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='downloads',
            field=models.IntegerField(null=True),
        ),
    ]
