# Generated by Django 4.0.3 on 2022-03-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_upload_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Fashion', 'Fashion'), ('Technology', 'Technology'), ('Science', 'Science')], max_length=200, null=True),
        ),
    ]
