# Generated by Django 4.0.3 on 2022-03-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_upload_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='downloads',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='uploads',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Fashion', 'Fashion'), ('Technology', 'Technology'), ('Science', 'Science'), ('Potrait', 'Potrait'), ('Landscape', 'Landscape')], max_length=200, null=True),
        ),
    ]
