# Generated by Django 4.0.3 on 2022-03-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_account_downloads_alter_account_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='downloads',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='uploads',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
