# Generated by Django 4.0.3 on 2022-04-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_upload_account_account_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='upload',
        ),
        migrations.AddField(
            model_name='upload',
            name='account',
            field=models.ManyToManyField(null=True, to='website.account'),
        ),
    ]
