# Generated by Django 4.0.3 on 2022-04-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_remove_account_upload_upload_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='account',
            field=models.ManyToManyField(to='website.account'),
        ),
    ]
