# Generated by Django 4.0.3 on 2022-04-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_upload_account_upload_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.account'),
        ),
    ]
