# Generated by Django 4.0.3 on 2022-04-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_upload_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.account'),
        ),
    ]
