# Generated by Django 4.0.3 on 2022-04-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_account_profile_pic_alter_upload_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.svg', null=True, upload_to='profiles/'),
        ),
    ]
