# Generated by Django 4.0.3 on 2022-08-08 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.account'),
        ),
    ]
