# Generated by Django 4.0.3 on 2022-08-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_upload_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='caption',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='category',
            field=models.CharField(choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape'), ('Sports', 'Sports'), ('Fashion', 'Fashion'), ('Technology', 'Technology'), ('Science', 'Science'), ('Food', 'Food')], max_length=200, null=True),
        ),
    ]
